import { z } from 'zod';
import type { OperationRegistry } from './registry.js';

const endpointSchema = z.object({
  family_id: z.string().regex(/^T(?:0[1-9]|1[0-2])$/u),
  http_method: z.enum(['GET', 'POST']),
  route: z.string().min(1),
  tool: z.string().regex(/^testrail_[a-z][a-z0-9_]*$/u),
  driver_method: z.string().regex(/^[a-zA-Z]+\.[a-zA-Z]+$/u),
  pagination: z.object({
    kind: z.enum(['none', 'controlled', 'response_driven']),
    page_method: z.string().nullable(),
    all_method: z.string().nullable(),
  }),
});

export type InventoryEndpoint = z.infer<typeof endpointSchema>;

/** The pinned inventory is independent of implementation registration. */
export function parseInventory(input: unknown): readonly InventoryEndpoint[] {
  const inventory = z.object({ operations: z.array(endpointSchema) }).parse(input).operations;
  const tools = new Set<string>();
  const routes = new Set<string>();
  const bindings = new Set<string>();
  for (const entry of inventory) {
    const route = `${entry.http_method} ${entry.route}`;
    if (tools.has(entry.tool) || routes.has(route) || bindings.has(entry.driver_method)) {
      throw new Error(`Duplicate inventory identity: ${entry.tool}`);
    }
    const token = entry.route.split('/')[0];
    if (entry.tool !== `testrail_${token}` ||
        (entry.pagination.kind === 'none') !== (entry.pagination.page_method === null && entry.pagination.all_method === null) ||
        (entry.pagination.kind !== 'none' && (entry.pagination.page_method === null || entry.pagination.all_method === null))) {
      throw new Error(`Inconsistent inventory identity: ${entry.tool}`);
    }
    tools.add(entry.tool);
    routes.add(route);
    bindings.add(entry.driver_method);
  }
  return inventory;
}

export interface ParityDifference {
  readonly tool: string;
  readonly field: string;
  readonly expected: string | null;
  readonly actual: string | null;
}

export interface ParityReport {
  readonly missing: readonly InventoryEndpoint[];
  readonly extra: readonly string[];
  readonly differences: readonly ParityDifference[];
}

export function compareRegistry(registry: OperationRegistry, inventory: readonly InventoryEndpoint[]): ParityReport {
  const expected = new Map(inventory.map((entry) => [entry.tool, entry]));
  const missing = inventory.filter((entry) => registry.get(entry.tool) === undefined);
  const extra: string[] = [];
  const differences: ParityDifference[] = [];
  for (const entry of registry.entries) {
    const baseline = expected.get(entry.tool);
    if (baseline === undefined) {
      extra.push(entry.tool);
      continue;
    }
    const compare = (field: string, expectedValue: string | null, actual: string | null): void => {
      if (expectedValue !== actual) differences.push({ tool: entry.tool, field, expected: expectedValue, actual });
    };
    compare('method', baseline.http_method, entry.method);
    compare('route', baseline.route, entry.route);
    compare('family', baseline.family_id, entry.family);
    compare('driver_binding', baseline.driver_method, entry.driverBinding);
    compare('pagination.kind', baseline.pagination.kind, entry.pagination.kind);
    compare('pagination.page_binding', baseline.pagination.page_method, entry.pagination.kind === 'none' ? null : entry.pagination.page.binding);
    compare('pagination.all_binding', baseline.pagination.all_method, entry.pagination.kind === 'none' ? null : entry.pagination.all.binding);
  }
  return { missing, extra, differences };
}

/** Partial mode permits missing families, never incorrect or extra entries. */
export function assertRegistryParity(report: ParityReport, complete: boolean): void {
  const problems = [
    ...report.extra.map((tool) => `Extra tool: ${tool}`),
    ...report.differences.map(({ tool, field, expected, actual }) => `${tool} ${field}: expected ${expected}, received ${actual}`),
    ...(complete ? report.missing.map((entry) => `Missing: ${entry.http_method} ${entry.route} -> ${entry.tool} -> ${entry.driver_method}`) : []),
  ];
  if (problems.length > 0) throw new Error(problems.join('\n'));
}

export function renderRegistryReference(registry: OperationRegistry, inventory: readonly InventoryEndpoint[]): string {
  const report = compareRegistry(registry, inventory);
  assertRegistryParity(report, false);
  const lines = [
    '# Generated operation reference',
    '',
    'Generated by `npm run registry:generate`. Edit endpoint definitions and the independent inventory, then regenerate.',
    '',
    `Implemented registrations: **${registry.entries.length}/${inventory.length}**. Missing registrations remain assigned to T01–T12; this is not a serving MCP catalog. F08 wires the runtime.`,
    '',
  ];
  for (const entry of registry.entries) {
    lines.push(
      `## ${entry.tool}`, '', entry.description, '',
      `REST: \`${entry.method} ${entry.route}\`. Driver: \`${entry.driverBinding}\`. Family: ${entry.family}.`, '',
      `TestRail effect: \`${entry.effects.testRail}\`. Driver retry policy: \`${entry.retry}\`. Local file behavior: \`${entry.files.kind}\`.`, '',
      '```json', JSON.stringify({ annotations: entry.annotations, inputSchema: entry.jsonSchema, argumentMap: entry.argumentMap }, null, 2), '```', '',
    );
  }
  lines.push('## Pending endpoint registrations', '', '| Tool | REST endpoint | Driver binding | Family |', '| --- | --- | --- | --- |');
  for (const entry of report.missing) {
    lines.push(`| \`${entry.tool}\` | \`${entry.http_method} ${entry.route}\` | \`${entry.driver_method}\` | ${entry.family_id} |`);
  }
  return `${lines.join('\n')}\n`;
}
